# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-11 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.ImageField(upload_to='media/images/')),
                ('description', models.TextField()),
            ],
        ),
    ]
