# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_work_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
        ),
    ]
