# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-20 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180518_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='sample',
            field=models.ImageField(upload_to='media'),
        ),
    ]
