# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-14 20:59
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180521_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
